/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_lame_longer_LameActivity */

#ifndef _Included_cn_lame_longer_LameActivity
#define _Included_cn_lame_longer_LameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_lame_longer_LameActivity
 * Method:    convertMp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_lame_longer_LameActivity_convertMp3
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
